[package]
name = "chess-move-gen"
description = "Fast chess move generation library"
version = "0.2.0"
authors = ["Peter Ellis Jones <pete@peterellisjones.com>"]
homepage = "https://github.com/peterellisjones/rust_move_gen"
repository = "https://github.com/peterellisjones/rust_move_gen.git"
keywords = ["chess"]
categories = ["game-engines"]
license = "MIT"
include = [
    "src/*.rs",
    "Cargo.toml",
    "LICENSE.txt"
]

[dependencies]
rand = "0.*"
unindent = "0.*"
simd = "0.*"