[package]
name = "chess-move-gen"
description = "Fast chess move generation library. Uses SIMD for fast sliding piece move generation"
version = "0.5.2"
authors = ["Peter Ellis Jones <pete@peterellisjones.com>"]
homepage = "https://github.com/peterellisjones/rust_move_gen"
repository = "https://github.com/peterellisjones/rust_move_gen.git"
keywords = ["chess"]
categories = ["game-engines"]
license = "MIT"
include = [
    "src/*.rs",
    "Cargo.toml",
    "LICENSE.txt"
]

[dependencies]
rand = "0.5"
unindent = "0.1.3"
simd = "0.2.2"
